spring.application.name=QuanLyQuanAnBinhDan

# === 1. CẤU HÌNH KẾT NỐI POSTGRESQL ===
spring.datasource.url=jdbc:postgresql://localhost:5432/db_quanliquan
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# === 2. CẤU HÌNH HIBERNATE / JPA ===
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# === 3. CẤU HÌNH SERVER ===
server.port=8082

# === 4. CẤU HÌNH KHỞI TẠO DỮ LIỆU ===
spring.jpa.defer-datasource-initialization=true
# Vẫn giữ nguyên thiết lập tắt tự động chạy data.sql của bạn
spring.sql.init.mode=never

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always